Repository kcm0147/Anabada_Project, pull requests merged in 2021-06, with the labels that each got.

#57 feat:add idCheck
  backend/src/main/java/com/auction/anabada/user/api/UserApiController.java
  backend/src/main/java/com/auction/anabada/user/service/UserService.java
Labels: Spring Boot, enhancement

#60 fix: set paging and http method for retrieving best items & searchs
  backend/src/main/java/com/auction/anabada/item/api/ItemApiController.java
  backend/src/main/java/com/auction/anabada/item/repository/ItemRepository.java
  backend/src/main/java/com/auction/anabada/search/repository/SearchRepository.java
Labels: Spring Boot, bug, enhancement

#62 fix: LIKE Query for querying name of item to find
  backend/src/main/java/com/auction/anabada/item/repository/ItemRepository.java
Labels: Spring Boot, bug, enhancement

#66 feat:add profileImage
  backend/src/main/java/com/auction/anabada/biddetail/dto/SimpleBidsDto.java
  backend/src/main/java/com/auction/anabada/item/domain/Item.java
  backend/src/main/java/com/auction/anabada/item/dto/EnrollItemDto.java
  backend/src/main/java/com/auction/anabada/item/dto/ItemDto.java
  backend/src/main/java/com/auction/anabada/item/service/ItemService.java
Labels: Spring Boot, enhancement

#68 Feat/issue 26/enroll item
  backend/src/main/java/com/auction/anabada/biddetail/dto/SimpleBidsDto.java
  backend/src/main/java/com/auction/anabada/item/domain/Item.java
  backend/src/main/java/com/auction/anabada/item/dto/EnrollItemDto.java
  backend/src/main/java/com/auction/anabada/item/dto/ItemDto.java
  backend/src/main/java/com/auction/anabada/saleItem/api/SaleItemApiController.java
Labels: Spring Boot, enhancement

#72 feat: add retrieving their own enrolled saleItems
  backend/src/main/java/com/auction/anabada/user/api/UserApiController.java
  backend/src/main/java/com/auction/anabada/user/service/UserService.java
Labels: Spring Boot, enhancement

#75 fix: LocalDatetime -> String
  backend/src/main/java/com/auction/anabada/item/dto/EnrollItemDto.java
Labels: Spring Boot, enhancement

#78 feat: simplebids add lastUserPrice and lastAuctionPrice
  backend/src/main/java/com/auction/anabada/biddetail/dto/SimpleBidsDto.java
  backend/src/main/java/com/auction/anabada/biddetail/service/BidService.java
  backend/src/main/java/com/auction/anabada/buyItem/service/BuyItemService.java
  backend/src/main/java/com/auction/anabada/item/domain/Item.java
  backend/src/main/java/com/auction/anabada/item/service/ItemService.java
  backend/src/main/java/com/auction/anabada/user/api/UserApiController.java
Labels: Spring Boot, enhancement

#79 feat:add enrollitem and bids fix
  backend/src/main/java/com/auction/anabada/item/domain/Item.java
  backend/src/main/java/com/auction/anabada/item/service/ItemService.java
  backend/src/main/java/com/auction/anabada/user/service/UserService.java
Labels: Spring Boot, enhancement

#81 fix: LIKE Query for retrieving item by name
  backend/src/main/java/com/auction/anabada/item/repository/ItemRepository.java
Labels: Spring Boot, bug

#84 feat: add item description
  backend/src/main/java/com/auction/anabada/item/domain/Item.java
  backend/src/main/java/com/auction/anabada/item/dto/EnrollItemDto.java
Labels: Spring Boot, enhancement

#88 Feat/issue 86/wish item
  backend/src/main/java/com/auction/anabada/item/domain/Item.java
  backend/src/main/java/com/auction/anabada/user/api/UserApiController.java
  backend/src/main/java/com/auction/anabada/user/domain/User.java
  backend/src/main/java/com/auction/anabada/user/service/UserService.java
  backend/src/main/java/com/auction/anabada/wishitem/api/WishItemApiController.java
  backend/src/main/java/com/auction/anabada/wishitem/domain/WishItem.java
  backend/src/main/java/com/auction/anabada/wishitem/dto/WishItemDto.java
  backend/src/main/java/com/auction/anabada/wishitem/repository/WishItemRepository.java
  backend/src/main/java/com/auction/anabada/wishitem/service/WishItemService.java
Labels: Spring Boot, enhancement

#90 feat: fix image process from encoding base64 to saving image file
  backend/src/main/java/com/auction/anabada/biddetail/dto/DetailBidsDto.java
  backend/src/main/java/com/auction/anabada/biddetail/dto/SimpleBidsDto.java
  backend/src/main/java/com/auction/anabada/biddetail/service/BidService.java
  backend/src/main/java/com/auction/anabada/item/api/ItemApiController.java
  backend/src/main/java/com/auction/anabada/item/domain/Item.java
  backend/src/main/java/com/auction/anabada/item/dto/EnrollItemDto.java
  backend/src/main/java/com/auction/anabada/item/dto/ItemDto.java
  backend/src/main/java/com/auction/anabada/saleItem/api/SaleItemApiController.java
  backend/src/main/java/com/auction/anabada/user/api/UserApiController.java
  backend/src/main/java/com/auction/anabada/user/service/UserService.java
Labels: Spring Boot, enhancement

#92 fix: remove WishItemDto
  backend/src/main/java/com/auction/anabada/wishitem/dto/WishItemDto.java
Labels: Spring Boot, bug

#93 fix: remove unused import statement
  backend/src/main/java/com/auction/anabada/wishitem/service/WishItemService.java
Labels: Spring Boot, bug

#96 Feat/issue 16/item image
  backend/src/main/java/com/auction/anabada/item/domain/Item.java
  backend/src/main/java/com/auction/anabada/item/dto/EnrollItemDto.java
  backend/src/main/java/com/auction/anabada/item/dto/ItemInfo.java
  backend/src/main/java/com/auction/anabada/saleItem/api/SaleItemApiController.java
  backend/src/main/resources/static/images/default.jpg
Labels: Spring Boot, enhancement

#104 feat: add webConfig to get image files with url
  backend/src/main/java/com/auction/anabada/config/WebConfig.java
Labels: Spring Boot, enhancement

#110 fix: fix imagePath
  backend/src/main/java/com/auction/anabada/item/dto/EnrollItemDto.java
Labels: Spring Boot, enhancement

#112 feat: add adjusting interestCnt of WishItems
  backend/src/main/java/com/auction/anabada/item/domain/Item.java
  backend/src/main/java/com/auction/anabada/item/service/ItemService.java
  backend/src/main/java/com/auction/anabada/saleItem/api/SaleItemApiController.java
  backend/src/main/java/com/auction/anabada/wishitem/api/WishItemApiController.java
  backend/src/main/java/com/auction/anabada/wishitem/domain/WishItem.java
  backend/src/main/java/com/auction/anabada/wishitem/service/WishItemService.java
Labels: Spring Boot, enhancement

#114 fix: error to search name of item to find
  client/src/components/search/SearchResult.js
Labels: bug, react

#115 fix: prevent user from making a bid with exception cases
  backend/src/main/java/com/auction/anabada/buyItem/service/BuyItemService.java
Labels: Spring Boot, bug

#126 fix: not allow to count empty search string
  backend/src/main/java/com/auction/anabada/item/service/ItemService.java
  backend/src/main/java/com/auction/anabada/search/service/SearchService.java
Labels: Spring Boot, bug
